version: '3.8'

services:
  django:
    build: .
    command: python -m uvicorn trend_link.asgi:application --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
    environment:
      - ENVIRONMENT=development
      - POSTGRES_DB=mydbname
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
    volumes:
      - .:/app
    working_dir: /app/trend_link

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydbname
      - POSTGRES_USER=myuser  
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./trend_link/nginx.conf:/etc/nginx/conf.d/default.conf
    
volumes:
  postgres_data:
