version: '3.8'

services:
  django:
    build: .
    command: python -m uvicorn trend_link.asgi:application --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app/trend_link

  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./trend_link/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./trend_link/trend_link/static:/app/trend_link/trend_link/static
      - ./trend_link/trend_link/media:/app/trend_link/trend_link/media
    depends_on:
      - django

  redis:
    image: redis:latest
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data:
